version: '3.4'

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin@123
          POSTGRES_DB: ecomm_development
          PGDATA: /data/postgres
        volumes:
           - postgres:/data/postgres
        ports:
          - "5432:5432"
        hostname: postgres
        networks:
          - postgres
        restart: unless-stopped
    ecomm:
        image: ${DOCKER_REGISTRY-}ecomm
        depends_on: 
            - postgres
        build:
            context: .
            dockerfile: Ecomm/Dockerfile
        ports:
          - "3000:80"
        networks:
          - postgres
networks:
    postgres:
        driver: bridge

volumes:
    postgres: